In [3]:
# Load an excel File
import pandas as pd

df = pd.read_excel('R:/Projects/Market Analysis and Database Records/Access Sales Data Databse Project/SC Sales Data/SC_All_Sales_Data.xlsx', sheet_name = 'Buildings')

df.head()

,Plan_Number_Clean,Building,Development_Type,Lots,Suburb,Geocode_Address,Postcode,First_Sale,Lon,Lat,First_Sale_Year
0,SP256115,SOVEREIGN RESIDENCE,Other,2.0,Pelican Waters,61 SOVEREIGN CRCT Pelican Waters QLD AUSTRALIA...,4551.0,2014-01-22,153.096575,-26.847711,2014
1,SP256116,SYLVIE PLACE,Other,2.0,Pelican Waters,11 CARNELL ST Pelican Waters QLD AUSTRALIA 4551,4551.0,2013-08-01,153.095573,-26.847303,2013
2,SP273640,THE CROFT,Other,2.0,Pelican Waters,8 FORSTER PL Pelican Waters QLD AUSTRALIA 4551,4551.0,2016-01-12,153.097823,-26.845529,2016
3,SP273646,TOOR,Other,2.0,Pelican Waters,5 TOORINGOOR CL Pelican Waters QLD AUSTRALIA 4551,4551.0,2017-04-24,153.096626,-26.844920,2017
4,GTP121,BELLVIEW LODGE,Other,2.0,Golden Beach,34 BOOKER PDE Golden Beach QLD AUSTRALIA 4551,4551.0,1989-07-03,153.111697,-26.840294,1989